---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	model(model)
	PIIMiddleware\5bemail\5d\2ebefore_model(PIIMiddleware[email].before_model)
	PIIMiddleware\5bemail\5d\2eafter_model(PIIMiddleware[email].after_model)
	PIIMiddleware\5bcredit_card\5d\2ebefore_model(PIIMiddleware[credit_card].before_model)
	PIIMiddleware\5bcredit_card\5d\2eafter_model(PIIMiddleware[credit_card].after_model)
	__end__([<p>__end__</p>]):::last
	PIIMiddleware\5bcredit_card\5d\2eafter_model --> PIIMiddleware\5bemail\5d\2eafter_model;
	PIIMiddleware\5bcredit_card\5d\2ebefore_model -.-> __end__;
	PIIMiddleware\5bcredit_card\5d\2ebefore_model -.-> model;
	PIIMiddleware\5bemail\5d\2ebefore_model -.-> PIIMiddleware\5bcredit_card\5d\2ebefore_model;
	PIIMiddleware\5bemail\5d\2ebefore_model -.-> __end__;
	__start__ --> PIIMiddleware\5bemail\5d\2ebefore_model;
	model --> PIIMiddleware\5bcredit_card\5d\2eafter_model;
	PIIMiddleware\5bemail\5d\2eafter_model --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
